content/graph/2sat.h

The expression `1 - x&1` produces a warning since the compiler suggests that we should add parentheses so it becomes `(1 - x)&1`.
In this specific case however, we have that `(1 - x)&1 == 1 - (x&1) == !(x&1)`.
I suggest we use `!(x&1)`, but we could also pick any of the two others with parentheses.

Fix compiler warning in 2sat.h

---

content/graph/TopoSort.h

Before this change they were 1-indexed.

Fix indices in toposort

---

content/number-theory/MillerRabin.h

It's about 2x faster for <1e9 and 3x faster for ~1e15. 
Also, the determinism is nice. Currently, the probabilistic Miller Rabin with 15 iterations is expected to fail in about a thousand seconds worth of computation on worst case input.

Changed Miller Rabin to deterministic variant

---

.gitignore
content/numerical/FastFourierTransform.h
content/numerical/NumberTheoreticTransform.h
fuzz-tests/ntt.cpp

Since we rewrote the FFT and got a massive speedup, seems strange that the NTT has such a different implementation from the FFT.
This PR updates the NTT to be written in the style of the new FFT, and gets a 7-10x boost in performance from doing so: https://ideone.com/QJwGfE
This also includes an update to the fuzz test for ntt - A. because the new FFT implementation returns empty vector if either one of the input polynomials is empty, and that's the API I copied for the NTT, and B. because the new NTT now requires that all inputs be within the mod range.
This is still somewhat WIP - I have a couple questions/issues I need to investigate more (and some notes)
1. The conditional modular adds/subtracts add about 30% in performance UNLESS `O3` is enabled. If `O3` is enabled then it slows it …

Updated NTT to be similar to the rewritten FFT

---

build/kactlprocessor.py
content/contest/.vimrc
content/contest/chapter.tex
content/contest/hash-cpp.sh
content/contest/hash.sh

Done in a similar fashion to MIT's. Unlike MIT's, I elected to not do section hashing, and to simply hash everything that's printed.
Taking ecnerwala's suggestion, I believe I moved the hashing to the last pass of the preprocessor. I also decided to put first 5 chars of the hash in the header, which looks good imo.
Sometimes you can run into issues like this though: 
This might just be a quirk of my latex compilation, as it seems like it's possible for this to also overlap with the line number count as well.

Added hashing

---

README.md
build/kactl.tex
build/kactlpkg.sty

Seems like it was just a simple matter of altering `\lstset`.
We might want to add a flag or change colors? Not sure how to do that/what colors we should choose.

Added coloring to code snippets

---

content/number-theory/ModInverse.h
fuzz-tests/number-theory/Eratosthenes.cpp
fuzz-tests/number-theory/FracBinarySearch.cpp
fuzz-tests/number-theory/MillerRabin.cpp
fuzz-tests/number-theory/ModInverse.cpp
fuzz-tests/number-theory/ModSqrt.cpp
fuzz-tests/number-theory/ModSum.cpp
fuzz-tests/number-theory/ModularArithmetic.cpp
fuzz-tests/number-theory/continuedfractions.cpp
fuzz-tests/numerical/berlekampmassey.cpp

The only major change I made was to change the test for `modInverse.cpp`. Admittedly, I think the newer test is a weaker test than I was previously, but at least it automatically imports from `modInverse.h` now.
See #79.

Standardized fuzztests for number theory code

---

content/graph/Dinic.h
content/graph/chapter.tex

Comes in at 42 lines and 800 non-whitespace characters, compared to 36 lines and 592 non-whitespace characters for Edmonds-Karp, and 46 lines and 761 non-whitespace characters for Hopcroft-Karp. Note that about 4 of these lines and 100 of the characters are due to `addEdge` (whereas you need to add edges yourself for Edmonds-Karp).
Unluckily, it seems to run at `0.45` seconds on SPOJ MATCHING compared to `0.15` from Hopcroft-Karp... In addition, it doesn't return the matches themselves like Hopcroft-Karp it does.
For now I haven't included it in the document - I think that's another discussion. See #75 .

Added implementation of Dinic's

---

build/kactlpkg.sty

Something about the coloring seemed off... 
I realized it was because I forgot to copy a line from the MIT's style file.
Current: 
After:

Added green coloring for basicstyle

---

content/data-structures/HashMap.h

See https://ideone.com/4frDuM.
```
8ms elapsed [custom hash insert]
2ms elapsed [custom hash read]
2847ms elapsed [no hash insert]
1701ms elapsed [no hash read]
```
It's a worst case example, of course, but it's a fairly natural one. I insert `v, v<<1, v<<2, ... v<<40`. We see a >300x slowdown for both insertions and reads (8/2ms to 2847/1701ms respectively).
I also have some discussion about it on the original post under "A better hash function".
I also don't think the custom preallocation is a big deal. Maybe it's worth including since it's not that much more, but my benchmarks don't show much of an improvement (maybe 5-10%).
Fixes #86 .

Updated policy hashmap with custom hash

---

content/contest/template.cpp

`begin(x)` is a strict superset of what `x.begin()` can do.
See https://stackoverflow.com/questions/26290316/difference-between-vectorbegin-and-stdbegin
I realize that KACTL almost never uses C-style arrays, but we also save 2 characters from this :^)

Change x.begin() to begin(x)

---

content/graph/chapter.tex

2 reasons:
1. MinimumVertexCover depends on the bipartite matching algorithms.
1. I think it makes more sense to put the bipartite matching stuff together, before the general graph matching.

Moved minimum vertex cover next to bipartite matching

---

content/data-structures/SegmentTree.h

Using `NEUTRAL` instead of `LOW` makes the code more clear when using a different function.

Segment improvements

---

content/tex/kactlpkg.sty

For my own purely selfish reasons (ie: it's convenient for me to navigate through the pdf by clicking on it).
Otherwise it looks the same I believe.

Make the TOC clickable

---

fuzz-tests/data-structures/FenwickTree.cpp
fuzz-tests/data-structures/LazySegmentTree.cpp
fuzz-tests/data-structures/SegmentTree.cpp
fuzz-tests/data-structures/Treap.cpp
fuzz-tests/geometry/DelaunayTriangulation.cpp
fuzz-tests/geometry/FastDelaunay.cpp
fuzz-tests/geometry/SegmentIntersection.cpp
fuzz-tests/numerical/IntDeterminant.cpp
fuzz-tests/run-all.sh
runtests.sh

2 changes (other than minor test output changes):
1. Fixed segtree tests that were broken after the recent update.
2. Added a test runner that runs all the tests (ie: `.cpp` files in `fuzz-tests). 
Finally outputs this:

Added a test runner

---

content/geometry/CircleIntersection.h
fuzz-tests/geometry/CircleIntersection.cpp

3 main changes. I didn't understand why any of these existed in the first place so if there's a reason, I'll revert that change from this PR: 
1. Changed the API to return 0/1/2 depending on the number of intersection points. Currently, the function doesn't distinguish between 1 and 2 return points. I suppose this is the equivalent of testing for `strict` in functions like `inPolygon`.
2. Changed `out` from a pointer to a reference.
3. Removed the `d2 > r*r` check.  Is this check here for higher precision?

Updated CircleIntersection.h

---

content/geometry/ManhattanMST.h
fuzz-tests/geometry/ManhattanMST.cpp

The main API decision to make here is whether we want to include MST within the implementation or to just return the set of candidate edges.
If we want to include the MST within the implementation, then I think we should include the MST code inside the notebook elsewhere and call it from here.

Added Manhattan MST

---

content/geometry/ConvexHull.h

It says in the pdf that this function returns the *indices* of the convex hull. That's not correct any longer as it returns the actual points (see the return type and line 32).

Update documentation of ConvexHull.h

---

content/various/FastInput.h
content/various/chapter.tex

I remember we had some discussions about the most ergonomic API, feel free to suggest changes.
Other than that, there's 2 main decisions that we want to consider.
1. Using `fread` instead of `getchar_unlocked`. `fread` is about 2x faster, for a total of 6x faster than cin.
2. Augment this implementation to read in floats as well.
First one seems more worth it. It's fairly easy to read in floats if needed (by reading both parts and doing some manual division). In addition, if you're ever in the situation where you need fast IO you might as well use the fastest IO you can get.

Added fast input

---

content/graph/LCA.h
stress-tests/graph/LCA.cpp
stress-tests/utilities/genTree.h

Fixes #146. Removes 8 lines of code and 4 lines of description, and makes it more obvious how to use the LCA. At the same time, if you do need this, it's easy to re-introduce manually.

Remove distance from LCA

---

content/number-theory/MillerRabin.h
content/number-theory/ModMulLL.h
doc/modmul-proof.tex
stress-tests/number-theory/Factor.cpp
stress-tests/number-theory/MillerRabin.cpp
stress-tests/number-theory/ModMulLL.cpp

Changes `ull(ld(a) * ld(b) / ld(M))` -> `ull(1.L / M * a * b);` to win a small bit of performance when `M` is constant over consecutive modmuls, and to shave off a few characters. Also adds a 4-page proof for the new version being correct for up to `M < 0.394 * 2^64`. (Somewhat excessive I guess, but it was fun.)

Make modmul faster for constant moduli

---

content/number-theory/ModLog.h
stress-tests/number-theory/ModLog.cpp

This PR adds two new features to ModLog(a,b,m).
1. The return value is now smallest x > 0, instead of smallest x >= 0. This allows for being able to calculate the order of an element a by doing ModLog(a,1,m).
2. It is no longer required for a and m to be coprime.
The algorithm is a modified version of the standard baby-step giant-step method. The modification allows for even non-coprime input using an original idea of mine.
Standard baby-step giant-step is based around finding (i, j) such that a^(i * n) = b * a^j (mod m), where n > sqrt(m) and 0<i,j<=n. If a and m are coprime, then a^j has a modular inverse, which means a^(i * n - j) = b (mod m). 
The modification (allowing for non-coprime a and m) is based around the following idea.
Assume p^x is a prime power divisor of m.
Then we have …

More general ModLog

---

content/data-structures/LineContainer.h

This allows us to use the assignment operator `=` with `LineContainer` objects.
Without making it static, trying to do `line_container1 = line_container2;` results in a compilation error.

Make `LineContainer.inf` static

---

README.md

It's always a good idea to prefer relative links to refer files and
folders over their absolute link. This way, we can ensure people are
referring to correct file or folder, even if someone else has forked the
project.

Use relative link to refer files

---

content/geometry/LineHullIntersection.h

lineHull should take poly by reference to avoid copying. This improves runtime from linear to logarithmic.

Fix bug in LineHullIntersection.

---

content/graph/GlobalMinCut.h

Currently the cut returned by `GlobalMinCut.h` doesn't achieve the value of the minimal cut. This is also noted on the [Wikipedia](https://en.wikipedia.org/wiki/Stoer%E2%80%93Wagner_algorithm) page, which uses the same code - upto coding conventions. This PR fixes this problem.

fix wrong cut in global min cut

---

content/geometry/FastDelaunay.h
stress-tests/geometry/FastDelaunay.cpp

Makes it about 33% faster, and reduces memory usage from O(n log n) to O(n). See discussion in #194. Closes #193.

Use a freelist for FastDelaunay

---

content/math/chapter.tex

Seems like minuses should be there, as initial recurrence uses previous values of `a` on the right side of the equation.
Source: Combinatorics and Number Theory lection.
I didn't recompile pdf with this improvement.

Fixed signs in one of the recurrences' expressions

---

.github/workflows/ccpp.yml

The continuous integration was set up tu run in the master branch, but this repo uses a main branch

Run continuous integration in main branch

---

stress-tests/data-structures/LineContainer.cpp
stress-tests/geometry/CircleLine.cpp
stress-tests/geometry/CirclePolygon.cpp
stress-tests/geometry/CircleTangents.cpp
stress-tests/geometry/ConvexHull.cpp
stress-tests/geometry/LineProjectionReflection.cpp
stress-tests/geometry/ManhattanMST.cpp
stress-tests/geometry/PolygonUnion.cpp
stress-tests/geometry/SegmentIntersection.cpp
stress-tests/geometry/insidePolygon.cpp
stress-tests/graph/DirectedMST.cpp
stress-tests/graph/GomoryHu.cpp
stress-tests/graph/HLD.cpp
stress-tests/graph/LCA.cpp
stress-tests/graph/MaximumClique.cpp
stress-tests/graph/WeightedMatching.cpp
stress-tests/number-theory/Factor.cpp
stress-tests/numerical/NumberTheoreticTransform.cpp
stress-tests/strings/Zfunc.cpp
stress-tests/utilities/bench.h
stress-tests/utilities/genPolygon.h
stress-tests/utilities/genTree.h
stress-tests/utilities/randGeo.h
stress-tests/utilities/random.h
stress-tests/utilities/utils.h
stress-tests/various/FastKnapsack.cpp

Some tests had spaces in the indentation, in these pull request I changed them all be tabs, so that the tests have the same style that the code

Use tabs for indentation in all tests

---

content/data-structures/SegmentTree.h
content/geometry/CircleIntersection.h
content/geometry/SegmentIntersection.h
content/geometry/lineDistance.h
content/geometry/sideOf.h
content/geometry/sphericalDistance.h
content/graph/2sat.h
content/graph/FloydWarshall.h
content/graph/MinCut.h
content/numerical/GoldenSectionSearch.h
content/strings/KMP.h
content/strings/Zfunc.h
content/various/DivideAndConquerDP.h

In the descriptions of some of the codes the where very long lines. In this pull request y splitted them in to several lines so that the sorce code is more readable.
Note that this does not affect the latex output.

Add line breaks in some long lines of latex (in descriptions)

---

content/numerical/GoldenSectionSearch.h

Add the text "and no local maximum" in the description of golden section search (gss) to note that gss may not work well if the function has a local maximum in the interval

Add clarification on gss description

---

content/graph/MinCostMaxFlow.h

This PR improves 3 things:
1. Fixes the time complexity description, as mentioned in #217 
2. No longer uses quadratic memory (adjacency list instead of matrix). Quadratic memory was problematic on problems with sparse graphs such as [tourist](https://open.kattis.com/problems/tourist).
3. Allows parallell/double edges.
Empirically, it also seems to improve performance (see "improved MCMF" [here](https://docs.google.com/spreadsheets/d/11ucYantzFPazqAlAa3J3-wC3NPmcXl3OMAqFhnXPMr8/edit?usp=sharing))
Potential downsides of new implementation: 
1. Loops (edges from a node to itself) don't work (when would you ever want that, though?)
2. Uses pointers to easily reconstruct path, making some parts less readable.
It passes all stress tests and doesn't get any WA's on the kattis problems I've …

Improve MCMF

---

content/graph/HLD.h

now, HLD is less code && uses less memory
this change uses the observation that if `u` and `v` are on the same vertical path, then comparing depths is the same as comparing preorder values
I did run this test locally, and it passed https://github.com/kth-competitive-programming/kactl/blob/main/stress-tests/graph/HLD.cpp

remove depth array from HLD

---

content/tex/preprocessor.py

When I tried to build my university kactl version the involved line of code somehow got executed and raised an error. It seems to me it should be a raw string instead of a normal string with escape character "\k".

Fix unintended escape character

---

content/strings/SuffixArray.h

Fixes undefined behavior in the Suffix Array implementation caused by copying a value from the end iterator of the string. I was able to get a runtime error on a problem and then get accepted by making this change to the suffix array implementation only.

Fix undefined behavior in Suffix Array

---

content/data-structures/Treap.h

Using auto instead of pair in order to write less.

Simplifying treap insert

---

content/geometry/CirclePolygonIntersection.h
content/geometry/PolygonCut.h

Made the following changes
* change `p+d*t` to `q+d*(t-1)`. The problem is if `-a+sqrt(det) ≫ 1`, then the term `arg(v, q)` is supposed to be identically zero, however if `q ≈ (0, 0)` then it's possible that `p+d ≉ q` and `arg(v, q) ≉ 0`, which results in a large error. See `a.cpp` in the attached file below.
* even if `side != (s.cross(e, prev) < 0)` is true, it is possible that the 4 points are almost collinear that `lineInter` returns the second value being `(0, 0)`. With this change, whenever `(a < 0) != (b < 0)` then `0 ≤ a / (a - b) ≤ 1`, which means the point being pushed is always on the line between `prev` and `cur` i.e. no catastrophic error can happen. See `b.cpp` in the attached file below.
Attachment (demonstration of catastrophic failure): …

Fix some issues that may cause catastrophic floating point error
