kth-competitive-programming/kactl

content/graph/edmondsKarp.h
=> Use unordered_map for edmondsKarp

content/number-theory/factor.h
=> Fix factor.h

content/appendix/techniques.txt
Signed-off-by: anton <haglundanton+github@gmail.com>
=> Fix typo in techniques.txt

content/strings/SuffixArray.h
Shaved another line off - inspired by looking at my coach's ICPC notebook.
I already ran the fuzz tests (which pass).
=> Shaved another line off SuffixArray.h

content/numerical/FastFourierTransform.h, content/strings/Zfunc.h, content/strings/chapter.tex, fuzz-tests/zfunc.cpp
Featuring a fuzz-test now (thanks to Ludo Pulles).
=> Added Z-function and fuzz test

content/strings/Manacher.h
Currently Manacher's doesn't return the vector it calculates.
=> Made Manachers return the vector that it's calculating

content/numerical/Integrate.h, content/numerical/IntegrateAdaptive.h
See https://github.com/kth-competitive-programming/kactl/issues/23
I'm not really sure what the other point in that issue is talking about (what's k?). Plus, it seems like a pain to do :thinking: 
I checked the example and such to make sure it still compiles and works (shouldn't have changed any functionality...)
=> Switched integrate functions to use functors

fuzz-tests/data-structures/FenwickTree2d.cpp, fuzz-tests/data-structures/LazySegmentTree.cpp, fuzz-tests/data-structures/LineContainer.cpp, fuzz-tests/data-structures/LinkCutTree.cpp, fuzz-tests/data-structures/RMQ.cpp, fuzz-tests/data-structures/SegmentTree.cpp, fuzz-tests/data-structures/Treap.cpp
One note, random seeds are generally frowned upon for tests, as they make failed tests unreproducible.
Most of the DS tests are pretty good, so this is a very minor change.
See #79.
=> Standardized tests for data structures

content/geometry/PolygonCenter.h
Just shortened it a bit and modified it to use indices instead of pointers.
Also, it creates a typedef and then doesn't use it :thinking:
=> Cleaned up polygoncenter

content/geometry/MinimumEnclosingCircle.h, fuzz-tests/geometry/MinimumEnclosingCircle.cpp
It passes the fuzz tests, and is about 25% faster than the old code.
Also saves 11 lines.
=> Shortened Minimum Enclosing Circle

content/data-structures/SegmentTree.h
Meant to leave this as a review comment on previous PR, but I think this is a bit nicer. No `~1`
=> Modify iterative segtree condition

fuzz-tests/various/FastMod.cpp, fuzz-tests/various/IntervalContainer.cpp
=> Standardized 'various' fuzz-tests

content/number-theory/ModInverse.h, fuzz-tests/number-theory/ModInverse.cpp
This was a test I made worse previously - this makes it good again.
=> Improved modinverse test

content/geometry/lineDistance.h
Took a little bit of thinking - probably worth adding a short part about this.
=> Added short explanation to linedistance

content/numerical/BerlekampMassey.h
Don't see any reason to not include this.
=> Added time complexity for berlekamp massey

content/number-theory/ModSqrt.h
I think it's a good idea to give a mathematical description of what it computes. Otherwise, variable names could be slightly confusing.
=> Added slightly more description for modsqrt

content/geometry/CirclePolygonIntersection.h, content/numerical/BerlekampMassey.h, fuzz-tests/geometry/CirclePolygon.cpp, fuzz-tests/utilities/genPolygon.h
=> Added circle polygon intersection

content/number-theory/ModLog.h, content/number-theory/chapter.tex, fuzz-tests/number-theory/ModLog.cpp
I'm fairly surprised we don't have this, tbh.
We might want to add instructions for how to extend this to arbitary a and m. I don't remember how, but I think it's possible.
=> Added Discrete log

content/combinatorial/chapter.tex
Same stuff that was in the MIT 2019 notebook, just copy pasted. Added bernoulli numbers and labeled unrooted trees. Looks like this: ![](https://i.imgur.com/NOHnJLw.jpg)
=> Added MIT Math stuff

content/data-structures/RMQ.h
No particular reason there should be newlines here.
=> removed extraneous newlines from rmq

content/number-theory/Factor.h, content/number-theory/chapter.tex, content/tex/preprocessor.py, stress-tests/number-theory/Factor.cpp
Accumulates GCD calls, resulting in about a 6-10x runtime improvement.
I find that when teams use KACTL, they'll often replace an implementation with their own implementation if they don't understand why something was done. Implementation details is an opportunity to explain the tradeoffs that were made without taking up valuable document space. Much of this discussion has been done in chat or PR's previously - I think it's worth adding them in the code itself.
I chose the tag "Details".
=> Updated Pollard Rho (also added a details commands for implementation details)

content/graph/PushRelabel.h, stress-tests/graph/maxflow.cpp
Maybe I should have just pushed this.
=> Fixed inconsistencies between pushrelabel and dinic

content/graph/GomoryHu.h, content/graph/WeightedMatching.h, stress-tests/graph/WeightedMatching.cpp
I'll stress test it against MCMF tomorrow.
=> Updated Hungarian

content/number-theory/chapter.tex
I'm not sure what you meant by this: https://github.com/kth-competitive-programming/kactl/pull/159#discussion_r388126994
I'm not aware of such a version - are you thinking of what he reduced the problem to here? https://codeforces.com/blog/entry/53925
Looks like this:
=> Added mobius inversion

content/data-structures/MoQueries.h, content/data-structures/chapter.tex, doc/scripts/skip_headers, stress-tests/data-structures/MoQueries.cpp
Still remaining: something about queries on trees (comment or code, not sure).
=> Add MoQueries

content/graph/EdgeColoring.h, content/graph/chapter.tex, stress-tests/graph/EdgeColoring.cpp, stress-tests/utilities/genGraph.h, stress-tests/utilities/random.h
=> Add EdgeColoring

content/tex/kactlpkg.sty, content/tex/preprocessor.py
Python 2 has been dead for 3 years.
=> Drop python 2 support for preprocessor

content/graph/EdmondsKarp.h, content/numerical/MatrixInverse-mod.h, content/numerical/NumberTheoreticTransform.h
These lines had a with more than 63
=> Shorten some lines that where to long

content/contest/.bashrc, doc/scripts/compile-all.sh, doc/scripts/test-compiles.sh
In some places c++17 was used and in some others c++14, in this pull request I changed the c++14 ones to c++17
=> Use c++17 everywhere
